spring:
  application:
    name: hotels-backend

logging:
  level:
    org.springframework.web.client.RestTemplate: debug
    br.com.gigiodesenvolvimento.hotelsbackend.broker.client.BrokerHotelWSClient: debug

broker:
  hotels:
    url: https://cvcbackendhotel.herokuapp.com/hotels